# Generated by Django 5.2.16 on 2026-07-15 09:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remind_at', models.DateTimeField()),
                ('method', models.CharField(choices=[('in_app', 'In-app'), ('email', 'Email')], default='in_app', max_length=10)),
                ('sent', models.BooleanField(default=False)),
                ('message', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='events.event')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='tasks.task')),
            ],
            options={
                'ordering': ['remind_at'],
                'indexes': [models.Index(fields=['owner', 'remind_at', 'sent'], name='reminders_r_owner_i_e9cbe2_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('task__isnull', False), ('event__isnull', False), _connector='OR'), name='reminder_has_task_or_event')],
            },
        ),
    ]
